### ISSUE TITLE
Ability to detect when transitioning from offline->online?

### ISSUE THREAD

**Issue by broakenmedia** [zplesac/android_connectionbuddy#55]
Need to be immediately notified when registering still so i can display the appropriate UI, however i want to implement an "Offline Sync" type feature, which is only called when the app is transitioning from offline->online. Right now it is always called immediately when the activity is started due to the immediate notify.

**Comment by zplesac** [comment]
If I understood correctly - you would like that ConnectivityChangeListener.onConnectionChange(ConnectivityEvent event) is called only when connection changes from offline to online?

**Comment by broakenmedia** [comment]
Have solved this myself now. By tracking changes while offline only then checking for said changes when coming back online. About to create another issue with a request though!

**Comment by zplesac** [comment]
Ok, closing this.
