### ISSUE TITLE
Ability to manually send a connection status event

### ISSUE THREAD

**Issue by broakenmedia** [zplesac/android_connectionbuddy#57]
OK, so this library can truly only detect whether A: Wifi is ON/OFF and B: 3G is ON/OFF it does not actually know if for instance, 3G is enabled, but the user is out of credit on their phone, thus the internet is not TRULY available. At this point, I'm firing off a "ping check" with a google server to determine the true online state. Depending on the result of that call it would be great to be able to "override" ConnectionB to say, "The internet is ON/OFF" and propagate the usual callbacks

**Comment by zplesac** [comment]
Let's define the enhancements:
- ability to determine if device can in fact connect to WiFi or mobile network
- if user is on mobile network, determine if he can in fact issue an network request by pinging some remote server

Do you have any other suggestions?

**Comment by broakenmedia** [comment]
Well, i wouldn't say you yourself would need to implement those. I would probably say, let the library continue to be a check for "adapters being enabled" then place the pinging duties on the developer but provide a manual means with which to tell connection buddy that the connection is offline.

**Comment by zplesac** [comment]
Actually, I really like the idea to ping some remote server in order to determine if network request can be executed over mobile data. I'm going to add this to version 1.1.0, it could be really helpful.

You can use ConnectionBuddy.getInstance().hasNetworkConnection() to determine the connection state - it will check both WiFi and mobile network state and return false if connection is currently offline.

**Comment by broakenmedia** [comment]
Great stuff :+1:  :) hasNetworkConnection however will still really only check if that adapters are ON/Available. Without a ping of some sort it's impossible to tell! Not to worry though. I've just set this up myself manually for now.

Lastly, just a quick thing to help you implement. You'll probably want to use this url for pinging against:

```
http://clients1.google.com/generate_204
```

It's actually the URL google themselves use in Chrome etc.. to determine if the user is on a hotel wifi hotspot for example (i.e. Connected to wifi and a network but not actually got access to the internet)

**Comment by zplesac** [comment]
Thanks Joe, this is really excellent idea! I'll start working on it soon, this is probably going to be the last feature which will go into version 1.1.0.

**Comment by broakenmedia** [comment]
Glad to hear it! I look forward to using it :) 

Do let me know if you need me for anything!

**Comment by zplesac** [comment]
@xbroak Could you please take a look at #59 and provide me with some feedback? I think that this should cover all of the defined use-cases.

**Comment by broakenmedia** [comment]
@zplesac That was quick! I'm actually struggling to see anything to comment on. It's almost identical to what i'd implemented. Good job!

**Comment by zplesac** [comment]
Great, I'll merge the changes than into development and release new version soon.

**Comment by zplesac** [comment]
Merged.
